sudo: false
dist: trusty
language: perl
cache:
  directories:
  - extlib
perl:
# ~stretch
- "5.24-shrplib"
addons:
  apt:
    packages:
    # irssi build dependencies
    - elinks
    # script test dependencies
    - zsh
    # script dependencies
    - libdb-dev
    - libaspell-dev
    - libgirepository1.0-dev
    - gobject-introspection
    - gir1.2-notify-0.7 # for desktop-notify
    - xosd-bin # for osd
before_install:
- cpanm --quiet local::lib
- eval "$(perl -Mlocal::lib=$TRAVIS_BUILD_DIR/extlib)"
- git clone -q git://github.com/irssi/irssi irssi-head
- export PERL_MM_NONINTERACTIVE=1
install:
- |
  pushd irssi-head
  ./autogen.sh --prefix=$HOME/irssi_inst --with-perl=module 2>/dev/null | tail -n 17
  make >/dev/null 2>&1
  make install | grep -C3 \\\.libs\\\|bin/irssi
  popd
- |
  if [ $TRAVIS_PULL_REQUEST = false ] && [ $USE_ARTEFACTS_CACHE = yes ] && [ $EXTRACT_TEST_ARTEFACTS = yes ]; then
    env -u REPO_LOGIN_TOKEN ./_testing/travis/load-old-artefacts.zsh
  fi
- env -u REPO_LOGIN_TOKEN
  cpanm --quiet --installdeps --notest .
- env -u REPO_LOGIN_TOKEN
  ./_testing/autoinstall-perl-prereqs.zsh
- |
  pushd auto
  env -u REPO_LOGIN_TOKEN cpanm --quiet --installdeps --notest .
  popd
before_script:
- export PATH=$HOME/irssi_inst/bin:$PATH
- env -u REPO_LOGIN_TOKEN
  ./_testing/run-test.zsh
- |
  if [ $TRAVIS_PULL_REQUEST != false ]; then
    git diff --stat $TRAVIS_BRANCH
  fi
script:
- env -u REPO_LOGIN_TOKEN
  ./_testing/report-test.zsh
after_script:
- env -u REPO_LOGIN_TOKEN
  ./_testing/travis/show-failures.zsh
- |
  if [ $TRAVIS_PULL_REQUEST = false ] && $TRAVIS_SECURE_ENV_VARS; then
    env -u REPO_LOGIN_TOKEN perl ./_testing/update-scripts-yaml.pl
    ./_testing/travis/commit-scripts-yaml.zsh
  fi
- |
  if [ $TRAVIS_PULL_REQUEST = false ] && $TRAVIS_SECURE_ENV_VARS && [ $EXTRACT_TEST_ARTEFACTS = yes ]; then
    ./_testing/travis/extract-artefacts.zsh
  fi
branches:
  only:
  - master
env:
  global:
  - USE_ARTEFACTS_CACHE=yes
  - EXTRACT_TEST_ARTEFACTS=yes
